version: "3.9"
services:
  plate-engine:
    container_name: 'plate-detector-engine'
    build:
      context: .
      shm_size: "2gb"
    shm_size: "2gb"
    runtime: nvidia
    # command: bash -c "CUDA_LAUNCH_BLOCKING=1 python test.py"
    tty: true
    volumes:
      - ../:/home/plate-engine